### PR TITLE
added the image slider

### PR DESCRIPTION
**Pull request by devmusiczz**
image

### CODE REVIEW

**Comment by devmusiczz** [comment]
fix #11

**Comment by charann29** [comment]
@devmusiczz Can you please host it in github pages and put the link in read me file? That would be great.

Great work , Thanks for contributing..

**Comment by devmusiczz** [comment]
sure

**Comment by devmusiczz** [comment]
hey @charann29 , added the link in the readme file. Please merge the PR and add hacktoberfest-accepted label. Thanks!

**Comment by charann29** [comment]
@devmusiczz Merged. Thanks for contributing.

**Pull request merged**
